server:
  port: 9020

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: "dbmanager"
  datasource:
    url: jdbc:postgresql://postgres:5432/invoice
    driverClassName: org.postgresql.Driver
    username: invoice_user
    password: invoice_pwd
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order-inserts: true
        order-updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  depends_on:
    - postgres

  kafka:
    bootstrap-servers: kafka:9096
    consumer:
      group-id: "dbmanager-dlt-consumer"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      function:
        definition: incomingInvoice;sdiNotification;sentInvoice
    stream:
      bindings:
        incomingInvoice-in-0:
          group: ${spring.application.name}
          content-type: application/json
        sdiNotification-in-0:
          group: ${spring.application.name}
          content-type: application/json
        sentInvoice-in-0:
          group: ${spring.application.name}
          content-type: application/json
        publishSavedInvoice-out-0:
          destination: savedInvoice-in-0
          content-type: application/json
        publishOutgoingInvoice-out-0:
          destination: outgoingInvoice-in-0
          content-type: application/json
        business-dlt-out-0:
          destination: dbmanager.DLT
          content-type: application/json
      kafka:
        binder:
          brokers:
            - kafka:9092
          producer-properties:
            retries: 3
            retry.backoff.ms: 1000
            delivery.timeout.ms: 120000
        bindings:
          incomingInvoice-in-0:
            consumer:
              enableDlq: true
              dlqName: incoming-invoice.DLT
              max-attempts: 3
              back-off-initial-interval: 1000
              use-native-decoding: true
              back-off-max-interval: 10000
              back-off-multiplier: 2.0
          sdiNotification-in-0:
            consumer:
              enableDlq: true
              dlqName: sdi-notification.DLT
              max-attempts: 3
              back-off-initial-interval: 1000
              use-native-decoding: true
              back-off-max-interval: 10000
              back-off-multiplier: 2.0
          sentInvoice-in-0:
            consumer:
              enableDlq: true
              dlqName: sent-invoice.DLT
              max-attempts: 3
              use-native-decoding: true
              back-off-initial-interval: 1000
              back-off-max-interval: 10000
              back-off-multiplier: 2.0

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    web:
      exposure:
        include: "*"
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "dbmanager"
    description: "Invoice App DbManager Application"
    version: "1.0.0"

logging:
  level:
    com.experis.dbmanager: DEBUG
    org.springframework.cloud.stream: INFO
    org.springframework.kafka: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]" 

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1
