server:
  port: 9020

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: "dbmanager"
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice
    driverClassName: org.postgresql.Driver
    username: invoice_user
    password: invoice_pwd
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  depends_on:
    - postgres

  # --- Spring Kafka Producer/Consumer Configuration ---
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest # Inizia a leggere dal primo messaggio disponibile

  # --- Spring Cloud Stream Configuration ---
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      function:
        definition: consumeIncomingInvoice;consumeSdiNotification;consumeSentInvoice
      bindings:
        consumeIncomingInvoice-in-0:
          destination: INCOMING_INVOICE
          group: ${spring.application.name}
        consumeSdiNotification-in-0:
          destination: DSI_NOTIFICATION
          group: ${spring.application.name}
        consumeSentInvoice-in-0:
          destination: SENT_INVOICE
          group: ${spring.application.name}
        publishSavedInvoice-out-0:
          destination: SAVED_INCOMING_INVOICE
        publishOutgoingInvoice-out-0:
          destination: OUTGOING_INVOICE
        business-dlt-out-0:
          destination: business.DLT
      kafka:
        consumer:
          auto-offset-reset: earliest
        binder:
          brokers:
            - localhost:9096
          producer-properties:
            retries: 3
            retry.backoff.ms: 1000
            delivery.timeout.ms: 120000
        bindings:
          consumeIncomingInvoice-in-0:
            consumer:
              enableDlq: true
              dlqName: incoming-invoice.DLT
              max-attempts: 3
              back-off-initial-interval: 1000
              use-native-decoding: false
              header-mode: none
              back-off-max-interval: 10000
              back-off-multiplier: 2.0
          consumeSdiNotification-in-0:
            consumer:
              enableDlq: true
              dlqName: sdi-notification.DLT
              max-attempts: 3
              back-off-initial-interval: 1000
              use-native-decoding: true
              header-mode: none
              back-off-max-interval: 10000
              back-off-multiplier: 2.0
          consumeSentInvoice-in-0:
            consumer:
              enableDlq: true
              dlqName: sent-invoice.DLT
              max-attempts: 3
              back-off-initial-interval: 1000
              back-off-max-interval: 10000
              back-off-multiplier: 2.0

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "dbmanager"
    description: "Invoice App DbManager Application"
    version: "1.0.0"

logging:
  level:
    com:
      experis:
        dbmanager: DEBUG
    org:
      springframework:
        cloud:
          stream: DEBUG # Aumenta il logging per Spring Cloud Stream
        kafka: DEBUG # Aumenta il logging per Kafka
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]" 

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1
