build:
  version: "1.0"

receiver:
  sender: "Welcome to InvoiceApp Sender Microservice QA"
  contactDetails:
    name: "Giancarlo Cadei - Developer"
    email: "giancarlo.cadei@it.experis.com"
  onCallSupport:
    - (+39) 320 60 20 839
