server:
  port: 9010

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: "sender"
  profiles:
    active: "prod"

  # --- Configurazione Mail Server Locale (per simulare invio SdI) ---
  mail:
    host: localhost
    port: 1025 # Porta standard per mail server locali come MailHog o GreenMail
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.debug: true # Utile per il debug

  # --- Configurazione Spring Cloud Stream ---
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      function:
        definition: consumeOutgoingInvoice
      bindings:
        # Consumer: Legge le fatture da inviare
        consumeOutgoingInvoice-in-0:
          destination: OUTGOING_INVOICE
          group: ${spring.application.name}
          consumer:
            max-attempts: 3 # Ritenta 3 volte in caso di errore
            back-off-initial-interval: 100
            back-off-max-interval: 500
            back-off-multiplier: 2.0
            enableDlq: true
            dlqName: sender-outgoing.DLT

        # Producer: Scrive l'esito dell'invio
        publishSentInvoice-out-0:
          destination: SENT_INVOICE
      kafka:
        binder:
          brokers: kafka:9092 # Assicurati che sia l'indirizzo corretto

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

info:
  app:
    name: "sender"
    description: "Invoice App Sender Application"
    version: "1.0.0"

logging:
  level:
    com:
      experis:
        sender: DEBUG
    org.springframework.mail: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1
